### ISSUE TITLE
Error printing a C10 object (__repr__).

### ISSUE THREAD

**Issue by razed11** [atac/pychapter10#27]
I get the following when trying to print a `C10` object:

```
AttributeError: 'Buffer' object has no attribute 'name'
```

I believe this should be `self.file.io.name` though there may be some subtlety that I'm missing:

<img width="796" alt="image" src="https://user-images.githubusercontent.com/816621/163062475-15a6bbf7-c06f-4035-afe1-3205d9006b21.png">

**Comment by mcferrill** [comment]
Yep that looks right. Could you submit a pull request to that effect? Bonus points for tests.

**Comment by razed11** [comment]
@mcferrill I cloned, made the change, and added a test but I can't push it presumably because I'm not a member? I didn't fork because I assumed I could push a branch and that you had `master protected. What do you recommend?

```
(c10) $ git push origin issue-27 
ERROR: Permission to atac/pychapter10.git denied to razed11.
fatal: Could not read from remote repository.
```

**Comment by mcferrill** [comment]
No worries. I would suggest:
1. Fork the repo
2. Add your fork as another remote `git remote add fork <fork_repo>`
3. Push your branch to the forked repo `git push fork issue-27`
4. Make your PR from the resulting branch in your repo back into master on the main repo.

**Comment by razed11** [comment]
Simple enough. Done.

Thanks for the library. It helped me recover some critical telemetry.

**Comment by mcferrill** [comment]
Glad to hear it! Also, I know this is a small change, but I truly appreciate you giving back.

**Comment by razed11** [comment]
Well it was the least I could do.

My `pytest` chops aren't the greatest so I was happy to see you use `parameterize` to avoid the repeated code.
